export const ONLOAD = 'ONLOAD'
export const UNLOAD = 'UNLOAD'
export const SHOW_DIALOG = 'SHOW_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST'
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'

export const CREATE_INVITE_CODE_REQUEST = 'CREATE_INVITE_CODE_REQUEST'
export const CREATE_INVITE_CODE_SUCCESS = 'CREATE_INVITE_CODE_SUCCESS'

export const VERIFY_PASSWORD_REQUEST = 'VERIFY_PASSWORD_REQUEST'
export const VERIFY_PASSWORD_SUCCESS = 'VERIFY_PASSWORD_SUCCESS'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'

export const GET_COUPONS_LIST_REQUEST = 'GET_COUPONS_LIST_REQUEST'
export const GET_COUPONS_LIST_SUCCESS = 'GET_COUPONS_LIST_SUCCESS'

export const GET_COUPONS_INFO_REQUEST = 'GET_COUPONS_INFO_REQUEST'
export const GET_COUPONS_INFO_SUCCESS = 'GET_COUPONS_INFO_SUCCESS'

export const PUBLISH_COUPON_REQUEST = 'PUBLISH_COUPON_REQUEST'
export const PUBLISH_COUPON_SUCCESS = 'PUBLISH_COUPON_SUCCESS'

export const GET_USER_COUPON_LIST_REQUEST = 'GET_USER_COUPON_LIST_REQUEST'
export const GET_USER_COUPON_LIST_SUCCESS = 'GET_USER_COUPON_LIST_SUCCESS'

export const GET_USER_COUPON_INFO_REQUEST = 'GET_USER_COUPON_INFO_REQUEST'
export const GET_USER_COUPON_INFO_SUCCESS = 'GET_USER_COUPON_INFO_SUCCESS'

export const UPDATE_USER_COUPON_REQUEST = 'UPDATE_USER_COUPON_REQUEST'
export const UPDATE_USER_COUPON_SUCCESS = 'UPDATE_USER_COUPON_SUCCESS'

export const SOLD_OUT_COUPON_REQUEST = 'SOLD_OUT_COUPON_REQUEST'
export const SOLD_OUT_COUPON_SUCCESS = 'SOLD_OUT_COUPON_SUCCESS'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'

export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST'
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'

export const GET_ORDER_INFO_REQUEST = 'GET_ORDER_INFO_REQUEST'
export const GET_ORDER_INFO_SUCCESS = 'GET_ORDER_INFO_SUCCESS'

export const OPEN_COUPON_REQUEST = 'OPEN_COUPON_REQUEST'
export const OPEN_COUPON_SUCCESS = 'OPEN_COUPON_SUCCESS'

